<?php
/* ************************************************************************************************** */
/* File		: bmdbinfo.inc
/* Author	: Ashokkumar, Mano, Kumaran, Saravanan
/* Date		: 10-Dec-2007
/* ************************************************************************************************** */
/* Description	:
/*     This inc file have DB name, DB Username, DB Password, Table name array list
/* ************************************************************************************************** */

// Database Name //
$DBNAME['MATRIMONYMS'] = 'matrimonyms';
$DBNAME['MATRIMONY'] = 'matrimony';
$DBNAME['MATRIMONYMSINACTIVE'] = 'matrimonymsinactive';
$DBNAME['MATRIMONYLOG'] = 'matrimonylog';
$DBNAME['MATRIMONYCOMBO'] = 'matrimonycombo';
$DBNAME['ASSUREDCONTACT'] = 'assuredcontact';
$DBNAME['BMADMIN'] = 'bmadmin';
$DBNAME['PROFILEVERIFICATION'] = 'profileverification';
$DBNAME['MATRIMONYMS'] = 'matrimonyms';
$DBNAME['MATRIMONY'] = 'matrimony';
$DBNAME['ASTROLOGY'] = 'astrology';
$DBNAME['CLASSIFIED'] = 'classified';
$DBNAME['EVENTS'] = 'events';
$DBNAME['FRANCHISEE'] = 'franchisee';
$DBNAME['OFFERS'] = 'offers';
$DBNAME['ONLINESWAYAMVARAM'] = 'onlineswayamvaram';
$DBNAME['ONLINESWAYAMVARAMLOG'] = 'onlineswayamvaramlog';
$DBNAME['SMS'] = 'sms';
$DBNAME['WEDDINGDIRECTORY'] = 'weddingdirectory';
$DBNAME['MATRIOTHER'] = 'matriother';
$DBNAME['MAILSYSTEM'] = 'mailsystem';
$DBNAME['MOBILEALERTS'] = 'mobilealerts';
$DBNAME['MATCHWATCH'] = 'matchwatch';
$DBNAME['WAPMATRIMONY'] = 'wapmatrimony';
$DBNAME['PROFILEMATCH'] = 'profilematch';
$DBNAME['MESSENGER'] = 'messenger';
$DBNAME['ASSUREDCONTACTINTERFACE'] = 'assuredcontactinterface';
$DBNAME['TELEMARKETING'] = 'telemarketing';
$DBNAME['FRONTOFFICE'] = 'frontoffice';
$DBNAME['COLLECTIONINTERFACE'] = 'collectioninterface';
$DBNAME['BMSUPPORT'] = 'bmsupport';
$DBNAME['BMPAYMENT'] = 'bmpayment';
$DBNAME['BMSHARECJ'] = 'bmsharecj';
$DBNAME['ONLINEPAYMENT'] = 'onlinepayment';
$DBNAME['CJPAYMENT'] = 'cjpayment';
$DBNAME['TIEUPS'] = 'tieups';
$DBNAME['ASSUREDCONTACTLOG'] = 'assuredcontactlog';
$DBNAME['MATRIMONYBOUNCE'] = 'matrimonybounce';
$DBNAME['COMMUNITYMATRIMONY'] = 'communitymatrimony'; // Database for cbs members
$DBNAME['CBSMAILSYSTEM'] = 'cbsmailsystem'; // Database for cbs members


// Database Username & Password //
$DBINFO['USERNAME'] = 'User4ip';
$DBINFO['PASSWORD'] = 'tniV6gV1';

// Merge Table //
$MERGETABLE['FAMILYINFO'] = 'familyinfo';
$MERGETABLE['FILTERINFO'] = 'filterinfo';
$MERGETABLE['HOBBIESINFO'] = 'hobbiesinfo';
$MERGETABLE['LOGININFO'] = 'logininfo';
$MERGETABLE['MATCHWATCH'] = 'matchwatch';
$MERGETABLE['PHOTOINFO'] = 'photoinfo';
$MERGETABLE['MATRIMONYPROFILE'] = 'matrimonyprofile';

// Domain Wise Table //

$DOMAINTABLE['ASSAMESE']['FAMILYINFO'] = 'assamesefamilyinfo';
$DOMAINTABLE['BENGALI']['FAMILYINFO'] = 'bengalifamilyinfo';
$DOMAINTABLE['GUJARATI']['FAMILYINFO'] = 'gujaratifamilyinfo';
$DOMAINTABLE['HINDI']['FAMILYINFO'] = 'hindifamilyinfo';
$DOMAINTABLE['KANNADA']['FAMILYINFO'] = 'kannadafamilyinfo';
$DOMAINTABLE['KERALA']['FAMILYINFO'] = 'keralafamilyinfo';
$DOMAINTABLE['MARATHI']['FAMILYINFO'] = 'marathifamilyinfo';
$DOMAINTABLE['MARWADI']['FAMILYINFO'] = 'marwadifamilyinfo';
$DOMAINTABLE['ORIYA']['FAMILYINFO'] = 'oriyafamilyinfo';
$DOMAINTABLE['PARSI']['FAMILYINFO'] = 'parsifamilyinfo';
$DOMAINTABLE['PUNJABI']['FAMILYINFO'] = 'punjabifamilyinfo';
$DOMAINTABLE['SINDHI']['FAMILYINFO'] = 'sindhifamilyinfo';
$DOMAINTABLE['TAMIL']['FAMILYINFO'] = 'tamilfamilyinfo';
$DOMAINTABLE['TELUGU']['FAMILYINFO'] = 'telugufamilyinfo';
$DOMAINTABLE['URDU']['FAMILYINFO'] = 'urdufamilyinfo';
$DOMAINTABLE['KASHMIRI']['FAMILYINFO'] = 'kashmirifamilyinfo';
$DOMAINTABLE['RAJASTANI']['FAMILYINFO'] = 'rajastanifamilyinfo';



$DOMAINTABLE['ASSAMESE']['FILTERINFO'] = 'assamesefilterinfo';
$DOMAINTABLE['BENGALI']['FILTERINFO'] = 'bengalifilterinfo';
$DOMAINTABLE['GUJARATI']['FILTERINFO'] = 'gujaratifilterinfo';
$DOMAINTABLE['HINDI']['FILTERINFO'] = 'hindifilterinfo';
$DOMAINTABLE['KANNADA']['FILTERINFO'] = 'kannadafilterinfo';
$DOMAINTABLE['KERALA']['FILTERINFO'] = 'keralafilterinfo';
$DOMAINTABLE['MARATHI']['FILTERINFO'] = 'marathifilterinfo';
$DOMAINTABLE['MARWADI']['FILTERINFO'] = 'marwadifilterinfo';
$DOMAINTABLE['ORIYA']['FILTERINFO'] = 'oriyafilterinfo';
$DOMAINTABLE['PARSI']['FILTERINFO'] = 'parsifilterinfo';
$DOMAINTABLE['PUNJABI']['FILTERINFO'] = 'punjabifilterinfo';
$DOMAINTABLE['SINDHI']['FILTERINFO'] = 'sindhifilterinfo';
$DOMAINTABLE['TAMIL']['FILTERINFO'] = 'tamilfilterinfo';
$DOMAINTABLE['TELUGU']['FILTERINFO'] = 'telugufilterinfo';
$DOMAINTABLE['URDU']['FILTERINFO'] = 'urdufilterinfo';
$DOMAINTABLE['KASHMIRI']['FILTERINFO'] = 'kashmirifilterinfo';
$DOMAINTABLE['RAJASTANI']['FILTERINFO'] = 'rajastanifilterinfo';

$DOMAINTABLE['ASSAMESE']['HOBBIESINFO'] = 'assamesehobbiesinfo';
$DOMAINTABLE['BENGALI']['HOBBIESINFO'] = 'bengalihobbiesinfo';
$DOMAINTABLE['GUJARATI']['HOBBIESINFO'] = 'gujaratihobbiesinfo';
$DOMAINTABLE['HINDI']['HOBBIESINFO'] = 'hindihobbiesinfo';
$DOMAINTABLE['KANNADA']['HOBBIESINFO'] = 'kannadahobbiesinfo';
$DOMAINTABLE['KERALA']['HOBBIESINFO'] = 'keralahobbiesinfo';
$DOMAINTABLE['MARATHI']['HOBBIESINFO'] = 'marathihobbiesinfo';
$DOMAINTABLE['MARWADI']['HOBBIESINFO'] = 'marwadihobbiesinfo';
$DOMAINTABLE['ORIYA']['HOBBIESINFO'] = 'oriyahobbiesinfo';
$DOMAINTABLE['PARSI']['HOBBIESINFO'] = 'parsihobbiesinfo';
$DOMAINTABLE['PUNJABI']['HOBBIESINFO'] = 'punjabihobbiesinfo';
$DOMAINTABLE['SINDHI']['HOBBIESINFO'] = 'sindhihobbiesinfo';
$DOMAINTABLE['TAMIL']['HOBBIESINFO'] = 'tamilhobbiesinfo';
$DOMAINTABLE['TELUGU']['HOBBIESINFO'] = 'teluguhobbiesinfo';
$DOMAINTABLE['URDU']['HOBBIESINFO'] = 'urduhobbiesinfo';
$DOMAINTABLE['KASHMIRI']['HOBBIESINFO'] = 'kashmirihobbiesinfo';
$DOMAINTABLE['RAJASTANI']['HOBBIESINFO'] = 'rajastanihobbiesinfo';



$DOMAINTABLE['ASSAMESE']['LOGININFO'] = 'assameselogininfo';
$DOMAINTABLE['BENGALI']['LOGININFO'] = 'bengalilogininfo';
$DOMAINTABLE['GUJARATI']['LOGININFO'] = 'gujaratilogininfo';
$DOMAINTABLE['HINDI']['LOGININFO'] = 'hindilogininfo';
$DOMAINTABLE['KANNADA']['LOGININFO'] = 'kannadalogininfo';
$DOMAINTABLE['KERALA']['LOGININFO'] = 'keralalogininfo';
$DOMAINTABLE['MARATHI']['LOGININFO'] = 'marathilogininfo';
$DOMAINTABLE['MARWADI']['LOGININFO'] = 'marwadilogininfo';
$DOMAINTABLE['ORIYA']['LOGININFO'] = 'oriyalogininfo';
$DOMAINTABLE['PARSI']['LOGININFO'] = 'parsilogininfo';
$DOMAINTABLE['PUNJABI']['LOGININFO'] = 'punjabilogininfo';
$DOMAINTABLE['SINDHI']['LOGININFO'] = 'sindhilogininfo';
$DOMAINTABLE['TAMIL']['LOGININFO'] = 'tamillogininfo';
$DOMAINTABLE['TELUGU']['LOGININFO'] = 'telugulogininfo';
$DOMAINTABLE['URDU']['LOGININFO'] = 'urdulogininfo';
$DOMAINTABLE['KASHMIRI']['LOGININFO'] = 'kashmirilogininfo';
$DOMAINTABLE['RAJASTANI']['LOGININFO'] = 'rajastanilogininfo';


$DOMAINTABLE['ASSAMESE']['MATCHWATCH'] = 'assamesematchwatch';
$DOMAINTABLE['BENGALI']['MATCHWATCH'] = 'bengalimatchwatch';
$DOMAINTABLE['GUJARATI']['MATCHWATCH'] = 'gujaratimatchwatch';
$DOMAINTABLE['HINDI']['MATCHWATCH'] = 'hindimatchwatch';
$DOMAINTABLE['KANNADA']['MATCHWATCH'] = 'kannadamatchwatch';
$DOMAINTABLE['KERALA']['MATCHWATCH'] = 'keralamatchwatch';
$DOMAINTABLE['MARATHI']['MATCHWATCH'] = 'marathimatchwatch';
$DOMAINTABLE['MARWADI']['MATCHWATCH'] = 'marwadimatchwatch';
$DOMAINTABLE['ORIYA']['MATCHWATCH'] = 'oriyamatchwatch';
$DOMAINTABLE['PARSI']['MATCHWATCH'] = 'parsimatchwatch';
$DOMAINTABLE['PUNJABI']['MATCHWATCH'] = 'punjabimatchwatch';
$DOMAINTABLE['SINDHI']['MATCHWATCH'] = 'sindhimatchwatch';
$DOMAINTABLE['TAMIL']['MATCHWATCH'] = 'tamilmatchwatch';
$DOMAINTABLE['TELUGU']['MATCHWATCH'] = 'telugumatchwatch';
$DOMAINTABLE['URDU']['MATCHWATCH'] = 'urdumatchwatch';
$DOMAINTABLE['KASHMIRI']['MATCHWATCH'] = 'kashmirimatchwatch';
$DOMAINTABLE['RAJASTANI']['MATCHWATCH'] = 'rajastanimatchwatch';


$DOMAINTABLE['ASSAMESE']['PHOTOINFO'] = 'assamesephotoinfo';
$DOMAINTABLE['BENGALI']['PHOTOINFO'] = 'bengaliphotoinfo';
$DOMAINTABLE['GUJARATI']['PHOTOINFO'] = 'gujaratiphotoinfo';
$DOMAINTABLE['HINDI']['PHOTOINFO'] = 'hindiphotoinfo';
$DOMAINTABLE['KANNADA']['PHOTOINFO'] = 'kannadaphotoinfo';
$DOMAINTABLE['KERALA']['PHOTOINFO'] = 'keralaphotoinfo';
$DOMAINTABLE['MARATHI']['PHOTOINFO'] = 'marathiphotoinfo';
$DOMAINTABLE['MARWADI']['PHOTOINFO'] = 'marwadiphotoinfo';
$DOMAINTABLE['ORIYA']['PHOTOINFO'] = 'oriyaphotoinfo';
$DOMAINTABLE['PARSI']['PHOTOINFO'] = 'parsiphotoinfo';
$DOMAINTABLE['PUNJABI']['PHOTOINFO'] = 'punjabiphotoinfo';
$DOMAINTABLE['SINDHI']['PHOTOINFO'] = 'sindhiphotoinfo';
$DOMAINTABLE['TAMIL']['PHOTOINFO'] = 'tamilphotoinfo';
$DOMAINTABLE['TELUGU']['PHOTOINFO'] = 'teluguphotoinfo';
$DOMAINTABLE['URDU']['PHOTOINFO'] = 'urduphotoinfo';
$DOMAINTABLE['KASHMIRI']['PHOTOINFO'] = 'kashmiriphotoinfo';
$DOMAINTABLE['RAJASTANI']['PHOTOINFO'] = 'rajastaniphotoinfo';

$DOMAINTABLE['ASSAMESE']['MATRIMONYPROFILE'] = 'assamesematrimonyprofile';
$DOMAINTABLE['BENGALI']['MATRIMONYPROFILE'] = 'bengalimatrimonyprofile';
$DOMAINTABLE['GUJARATI']['MATRIMONYPROFILE'] = 'gujaratimatrimonyprofile';
$DOMAINTABLE['HINDI']['MATRIMONYPROFILE'] = 'hindimatrimonyprofile';
$DOMAINTABLE['KANNADA']['MATRIMONYPROFILE'] = 'kannadamatrimonyprofile';
$DOMAINTABLE['KERALA']['MATRIMONYPROFILE'] = 'keralamatrimonyprofile';
$DOMAINTABLE['MARATHI']['MATRIMONYPROFILE'] = 'marathimatrimonyprofile';
$DOMAINTABLE['MARWADI']['MATRIMONYPROFILE'] = 'marwadimatrimonyprofile';
$DOMAINTABLE['ORIYA']['MATRIMONYPROFILE'] = 'oriyamatrimonyprofile';
$DOMAINTABLE['PARSI']['MATRIMONYPROFILE'] = 'parsimatrimonyprofile';
$DOMAINTABLE['PUNJABI']['MATRIMONYPROFILE'] = 'punjabimatrimonyprofile';
$DOMAINTABLE['SINDHI']['MATRIMONYPROFILE'] = 'sindhimatrimonyprofile';
$DOMAINTABLE['TAMIL']['MATRIMONYPROFILE'] = 'tamilmatrimonyprofile';
$DOMAINTABLE['TELUGU']['MATRIMONYPROFILE'] = 'telugumatrimonyprofile';
$DOMAINTABLE['URDU']['MATRIMONYPROFILE'] = 'urdumatrimonyprofile';
$DOMAINTABLE['KASHMIRI']['MATRIMONYPROFILE'] = 'kashmirimatrimonyprofile';
$DOMAINTABLE['RAJASTANI']['MATRIMONYPROFILE'] = 'rajastanimatrimonyprofile';


$DOMAINTABLE['ASSAMESE']['RECEIVELOG'] = 'assamesereceivelog';
$DOMAINTABLE['BENGALI']['RECEIVELOG'] = 'bengalireceivelog';
$DOMAINTABLE['GUJARATI']['RECEIVELOG'] = 'gujaratireceivelog';
$DOMAINTABLE['HINDI']['RECEIVELOG'] = 'hindireceivelog';
$DOMAINTABLE['KANNADA']['RECEIVELOG'] = 'kannadareceivelog';
$DOMAINTABLE['KERALA']['RECEIVELOG'] = 'keralareceivelog';
$DOMAINTABLE['MARATHI']['RECEIVELOG'] = 'marathireceivelog';
$DOMAINTABLE['MARWADI']['RECEIVELOG'] = 'marwadireceivelog';
$DOMAINTABLE['ORIYA']['RECEIVELOG'] = 'oriyareceivelog';
$DOMAINTABLE['PARSI']['RECEIVELOG'] = 'parsireceivelog';
$DOMAINTABLE['PUNJABI']['RECEIVELOG'] = 'punjabireceivelog';
$DOMAINTABLE['SINDHI']['RECEIVELOG'] = 'sindhireceivelog';
$DOMAINTABLE['TAMIL']['RECEIVELOG'] = 'tamilreceivelog';
$DOMAINTABLE['TELUGU']['RECEIVELOG'] = 'telugureceivelog';
$DOMAINTABLE['URDU']['RECEIVELOG'] = 'urdureceivelog';
$DOMAINTABLE['KASHMIRI']['RECEIVELOG'] = 'kashmirireceivelog';
$DOMAINTABLE['RAJASTANI']['RECEIVELOG'] = 'rajastanireceivelog';


$DOMAINTABLE['ASSAMESE']['SENTLOG'] = 'assamesesentlog';
$DOMAINTABLE['BENGALI']['SENTLOG'] = 'bengalisentlog';
$DOMAINTABLE['GUJARATI']['SENTLOG'] = 'gujaratisentlog';
$DOMAINTABLE['HINDI']['SENTLOG'] = 'hindisentlog';
$DOMAINTABLE['KANNADA']['SENTLOG'] = 'kannadasentlog';
$DOMAINTABLE['KERALA']['SENTLOG'] = 'keralasentlog';
$DOMAINTABLE['MARATHI']['SENTLOG'] = 'marathisentlog';
$DOMAINTABLE['MARWADI']['SENTLOG'] = 'marwadisentlog';
$DOMAINTABLE['ORIYA']['SENTLOG'] = 'oriyasentlog';
$DOMAINTABLE['PARSI']['SENTLOG'] = 'parsisentlog';
$DOMAINTABLE['PUNJABI']['SENTLOG'] = 'punjabisentlog';
$DOMAINTABLE['SINDHI']['SENTLOG'] = 'sindhisentlog';
$DOMAINTABLE['TAMIL']['SENTLOG'] = 'tamilsentlog';
$DOMAINTABLE['TELUGU']['SENTLOG'] = 'telugusentlog';
$DOMAINTABLE['URDU']['SENTLOG'] = 'urdusentlog';
$DOMAINTABLE['KASHMIRI']['SENTLOG'] = 'kashmirisentlog';
$DOMAINTABLE['RAJASTANI']['SENTLOG'] = 'rajastanisentlog';


$DOMAINTABLE['ASSAMESE']['RECEIVEINTEREST'] = 'assamesereceiveinterest';
$DOMAINTABLE['BENGALI']['RECEIVEINTEREST'] = 'bengalireceiveinterest';
$DOMAINTABLE['GUJARATI']['RECEIVEINTEREST'] = 'gujaratireceiveinterest';
$DOMAINTABLE['HINDI']['RECEIVEINTEREST'] = 'hindireceiveinterest';
$DOMAINTABLE['KANNADA']['RECEIVEINTEREST'] = 'kannadareceiveinterest';
$DOMAINTABLE['KERALA']['RECEIVEINTEREST'] = 'keralareceiveinterest';
$DOMAINTABLE['MARATHI']['RECEIVEINTEREST'] = 'marathireceiveinterest';
$DOMAINTABLE['MARWADI']['RECEIVEINTEREST'] = 'marwadireceiveinterest';
$DOMAINTABLE['ORIYA']['RECEIVEINTEREST'] = 'oriyareceiveinterest';
$DOMAINTABLE['PARSI']['RECEIVEINTEREST'] = 'parsireceiveinterest';
$DOMAINTABLE['PUNJABI']['RECEIVEINTEREST'] = 'punjabireceiveinterest';
$DOMAINTABLE['SINDHI']['RECEIVEINTEREST'] = 'sindhireceiveinterest';
$DOMAINTABLE['TAMIL']['RECEIVEINTEREST'] = 'tamilreceiveinterest';
$DOMAINTABLE['TELUGU']['RECEIVEINTEREST'] = 'telugureceiveinterest';
$DOMAINTABLE['URDU']['RECEIVEINTEREST'] = 'urdureceiveinterest';
$DOMAINTABLE['KASHMIRI']['RECEIVEINTEREST'] = 'kashmirireceiveinterest';
$DOMAINTABLE['RAJASTANI']['RECEIVEINTEREST'] = 'rajastanireceiveinterest';


$DOMAINTABLE['ASSAMESE']['SENTINTEREST'] = 'assamesesentinterest';
$DOMAINTABLE['BENGALI']['SENTINTEREST'] = 'bengalisentinterest';
$DOMAINTABLE['GUJARATI']['SENTINTEREST'] = 'gujaratisentinterest';
$DOMAINTABLE['HINDI']['SENTINTEREST'] = 'hindisentinterest';
$DOMAINTABLE['KANNADA']['SENTINTEREST'] = 'kannadasentinterest';
$DOMAINTABLE['KERALA']['SENTINTEREST'] = 'keralasentinterest';
$DOMAINTABLE['MARATHI']['SENTINTEREST'] = 'marathisentinterest';
$DOMAINTABLE['MARWADI']['SENTINTEREST'] = 'marwadisentinterest';
$DOMAINTABLE['ORIYA']['SENTINTEREST'] = 'oriyasentinterest';
$DOMAINTABLE['PARSI']['SENTINTEREST'] = 'parsisentinterest';
$DOMAINTABLE['PUNJABI']['SENTINTEREST'] = 'punjabisentinterest';
$DOMAINTABLE['SINDHI']['SENTINTEREST'] = 'sindhisentinterest';
$DOMAINTABLE['TAMIL']['SENTINTEREST'] = 'tamilsentinterest';
$DOMAINTABLE['TELUGU']['SENTINTEREST'] = 'telugusentinterest';
$DOMAINTABLE['URDU']['SENTINTEREST'] = 'urdusentinterest';
$DOMAINTABLE['KASHMIRI']['SENTINTEREST'] = 'kashmirisentinterest';
$DOMAINTABLE['RAJASTANI']['SENTINTEREST'] = 'rajastanisentinterest';


$DOMAINTABLE['ASSAMESE']['REQUESTINFORECEIVED'] = 'assameserequestinforeceived';
$DOMAINTABLE['BENGALI']['REQUESTINFORECEIVED'] = 'bengalirequestinforeceived';
$DOMAINTABLE['GUJARATI']['REQUESTINFORECEIVED'] = 'gujaratirequestinforeceived';
$DOMAINTABLE['HINDI']['REQUESTINFORECEIVED'] = 'hindirequestinforeceived';
$DOMAINTABLE['KANNADA']['REQUESTINFORECEIVED'] = 'kannadarequestinforeceived';
$DOMAINTABLE['KERALA']['REQUESTINFORECEIVED'] = 'keralarequestinforeceived';
$DOMAINTABLE['MARATHI']['REQUESTINFORECEIVED'] = 'marathirequestinforeceived';
$DOMAINTABLE['MARWADI']['REQUESTINFORECEIVED'] = 'marwadirequestinforeceived';
$DOMAINTABLE['ORIYA']['REQUESTINFORECEIVED'] = 'oriyarequestinforeceived';
$DOMAINTABLE['PARSI']['REQUESTINFORECEIVED'] = 'parsirequestinforeceived';
$DOMAINTABLE['PUNJABI']['REQUESTINFORECEIVED'] = 'punjabirequestinforeceived';
$DOMAINTABLE['SINDHI']['REQUESTINFORECEIVED'] = 'sindhirequestinforeceived';
$DOMAINTABLE['TAMIL']['REQUESTINFORECEIVED'] = 'tamilrequestinforeceived';
$DOMAINTABLE['TELUGU']['REQUESTINFORECEIVED'] = 'telugurequestinforeceived';
$DOMAINTABLE['URDU']['REQUESTINFORECEIVED'] = 'urdurequestinforeceived';
$DOMAINTABLE['KASHMIRI']['REQUESTINFORECEIVED'] = 'kashmirirequestinforeceived';
$DOMAINTABLE['RAJASTANI']['REQUESTINFORECEIVED'] = 'rajastanirequestinforeceived';


$DOMAINTABLE['ASSAMESE']['REQUESTINFOSENT'] = 'assameserequestinfosent';
$DOMAINTABLE['BENGALI']['REQUESTINFOSENT'] = 'bengalirequestinfosent';
$DOMAINTABLE['GUJARATI']['REQUESTINFOSENT'] = 'gujaratirequestinfosent';
$DOMAINTABLE['HINDI']['REQUESTINFOSENT'] = 'hindirequestinfosent';
$DOMAINTABLE['KANNADA']['REQUESTINFOSENT'] = 'kannadarequestinfosent';
$DOMAINTABLE['KERALA']['REQUESTINFOSENT'] = 'keralarequestinfosent';
$DOMAINTABLE['MARATHI']['REQUESTINFOSENT'] = 'marathirequestinfosent';
$DOMAINTABLE['MARWADI']['REQUESTINFOSENT'] = 'marwadirequestinfosent';
$DOMAINTABLE['ORIYA']['REQUESTINFOSENT'] = 'oriyarequestinfosent';
$DOMAINTABLE['PARSI']['REQUESTINFOSENT'] = 'parsirequestinfosent';
$DOMAINTABLE['PUNJABI']['REQUESTINFOSENT'] = 'punjabirequestinfosent';
$DOMAINTABLE['SINDHI']['REQUESTINFOSENT'] = 'sindhirequestinfosent';
$DOMAINTABLE['TAMIL']['REQUESTINFOSENT'] = 'tamilrequestinfosent';
$DOMAINTABLE['TELUGU']['REQUESTINFOSENT'] = 'telugurequestinfosent';
$DOMAINTABLE['URDU']['REQUESTINFOSENT'] = 'urdurequestinfosent';
$DOMAINTABLE['KASHMIRI']['REQUESTINFOSENT'] = 'kashmirirequestinfosent';
$DOMAINTABLE['RAJASTANI']['REQUESTINFOSENT'] = 'rajastanirequestinfosent';


$DOMAINTABLE['ASSAMESE']['PAYMENTOPTIONS'] = 'assamesepaymentoptions';
$DOMAINTABLE['BENGALI']['PAYMENTOPTIONS'] = 'bengalipaymentoptions';
$DOMAINTABLE['GUJARATI']['PAYMENTOPTIONS'] = 'gujaratipaymentoptions';
$DOMAINTABLE['HINDI']['PAYMENTOPTIONS'] = 'hindipaymentoptions';
$DOMAINTABLE['KANNADA']['PAYMENTOPTIONS'] = 'kannadapaymentoptions';
$DOMAINTABLE['KERALA']['PAYMENTOPTIONS'] = 'keralapaymentoptions';
$DOMAINTABLE['MARATHI']['PAYMENTOPTIONS'] = 'marathipaymentoptions';
$DOMAINTABLE['MARWADI']['PAYMENTOPTIONS'] = 'marwadipaymentoptions';
$DOMAINTABLE['ORIYA']['PAYMENTOPTIONS'] = 'oriyapaymentoptions';
$DOMAINTABLE['PARSI']['PAYMENTOPTIONS'] = 'parsipaymentoptions';
$DOMAINTABLE['PUNJABI']['PAYMENTOPTIONS'] = 'punjabipaymentoptions';
$DOMAINTABLE['SINDHI']['PAYMENTOPTIONS'] = 'sindhipaymentoptions';
$DOMAINTABLE['TAMIL']['PAYMENTOPTIONS'] = 'tamilpaymentoptions';
$DOMAINTABLE['TELUGU']['PAYMENTOPTIONS'] = 'telugupaymentoptions';
$DOMAINTABLE['URDU']['PAYMENTOPTIONS'] = 'urdupaymentoptions';
$DOMAINTABLE['KASHMIRI']['PAYMENTOPTIONS'] = 'kashmiripaymentoptions';
$DOMAINTABLE['RAJASTANI']['PAYMENTOPTIONS'] = 'rajastanipaymentoptions';


$DOMAINTABLE['ASSAMESE']['PROFILENOTES'] = 'assameseprofilenotes';
$DOMAINTABLE['BENGALI']['PROFILENOTES'] = 'bengaliprofilenotes';
$DOMAINTABLE['GUJARATI']['PROFILENOTES'] = 'gujaratiprofilenotes';
$DOMAINTABLE['HINDI']['PROFILENOTES'] = 'hindiprofilenotes';
$DOMAINTABLE['KANNADA']['PROFILENOTES'] = 'kannadaprofilenotes';
$DOMAINTABLE['KERALA']['PROFILENOTES'] = 'keralaprofilenotes';
$DOMAINTABLE['MARATHI']['PROFILENOTES'] = 'marathiprofilenotes';
$DOMAINTABLE['MARWADI']['PROFILENOTES'] = 'marwadiprofilenotes';
$DOMAINTABLE['ORIYA']['PROFILENOTES'] = 'oriyaprofilenotes';
$DOMAINTABLE['PARSI']['PROFILENOTES'] = 'parsiprofilenotes';
$DOMAINTABLE['PUNJABI']['PROFILENOTES'] = 'punjabiprofilenotes';
$DOMAINTABLE['SINDHI']['PROFILENOTES'] = 'sindhiprofilenotes';
$DOMAINTABLE['TAMIL']['PROFILENOTES'] = 'tamilprofilenotes';
$DOMAINTABLE['TELUGU']['PROFILENOTES'] = 'teluguprofilenotes';
$DOMAINTABLE['URDU']['PROFILENOTES'] = 'urduprofilenotes';
$DOMAINTABLE['KASHMIRI']['PROFILENOTES'] = 'kashmiriprofilenotes';
$DOMAINTABLE['RAJASTANI']['PROFILENOTES'] = 'rajastaniprofilenotes';


$DOMAINTABLE['ASSAMESE']['PROFILESTATS'] = 'assameseprofilestats';
$DOMAINTABLE['BENGALI']['PROFILESTATS'] = 'bengaliprofilestats';
$DOMAINTABLE['GUJARATI']['PROFILESTATS'] = 'gujaratiprofilestats';
$DOMAINTABLE['HINDI']['PROFILESTATS'] = 'hindiprofilestats';
$DOMAINTABLE['KANNADA']['PROFILESTATS'] = 'kannadaprofilestats';
$DOMAINTABLE['KERALA']['PROFILESTATS'] = 'keralaprofilestats';
$DOMAINTABLE['MARATHI']['PROFILESTATS'] = 'marathiprofilestats';
$DOMAINTABLE['MARWADI']['PROFILESTATS'] = 'marwadiprofilestats';
$DOMAINTABLE['ORIYA']['PROFILESTATS'] = 'oriyaprofilestats';
$DOMAINTABLE['PARSI']['PROFILESTATS'] = 'parsiprofilestats';
$DOMAINTABLE['PUNJABI']['PROFILESTATS'] = 'punjabiprofilestats';
$DOMAINTABLE['SINDHI']['PROFILESTATS'] = 'sindhiprofilestats';
$DOMAINTABLE['TAMIL']['PROFILESTATS'] = 'tamilprofilestats';
$DOMAINTABLE['TELUGU']['PROFILESTATS'] = 'teluguprofilestats';
$DOMAINTABLE['URDU']['PROFILESTATS'] = 'urduprofilestats';
$DOMAINTABLE['KASHMIRI']['PROFILESTATS'] = 'kashmiriprofilestats';
$DOMAINTABLE['RAJASTANI']['PROFILESTATS'] = 'rajastaniprofilestats';



$DOMAINTABLE['ASSAMESE']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['BENGALI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['GUJARATI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['HINDI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['KANNADA']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['KERALA']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['MARATHI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['MARWADI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['ORIYA']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['PARSI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['PUNJABI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['SINDHI']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['TAMIL']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['TELUGU']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['URDU']['EXPINTACCEPTEDLIMIT'] = 'expintacceptedlimit';
$DOMAINTABLE['KASHMIRI']['EXPINTACCEPTEDLIMIT'] = 'kashmiriacceptedlimit';
$DOMAINTABLE['RAJASTANI']['EXPINTACCEPTEDLIMIT'] = 'rajastaniacceptedlimit';


$DOMAINTABLE['ASSAMESE']['BLOCKED'] = 'blocked';
$DOMAINTABLE['BENGALI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['GUJARATI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['HINDI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['KANNADA']['BLOCKED'] = 'blocked';
$DOMAINTABLE['KERALA']['BLOCKED'] = 'blocked';
$DOMAINTABLE['MARATHI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['MARWADI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['ORIYA']['BLOCKED'] = 'blocked';
$DOMAINTABLE['PARSI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['PUNJABI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['SINDHI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['TAMIL']['BLOCKED'] = 'blocked';
$DOMAINTABLE['TELUGU']['BLOCKED'] = 'blocked';
$DOMAINTABLE['URDU']['BLOCKED'] = 'blocked';
$DOMAINTABLE['KASHMIRI']['BLOCKED'] = 'blocked';
$DOMAINTABLE['RAJASTANI']['BLOCKED'] = 'blocked';


$DOMAINTABLE['ASSAMESE']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['BENGALI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['GUJARATI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['HINDI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['KANNADA']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['KERALA']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['MARATHI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['MARWADI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['ORIYA']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['PARSI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['PUNJABI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['SINDHI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['TAMIL']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['TELUGU']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['URDU']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['KASHMIRI']['BMVOICEPROFILE'] = 'bmvoiceprofile';
$DOMAINTABLE['RAJASTANI']['BMVOICEPROFILE'] = 'bmvoiceprofile';


$DOMAINTABLE['ASSAMESE']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['BENGALI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['GUJARATI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['HINDI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['KANNADA']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['KERALA']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['MARATHI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['MARWADI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['ORIYA']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['PARSI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['PUNJABI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['SINDHI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['TAMIL']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['TELUGU']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['URDU']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['KASHMIRI']['EMAILBOUNCE'] = 'emailbounce';
$DOMAINTABLE['RAJASTANI']['EMAILBOUNCE'] = 'emailbounce';


$DOMAINTABLE['ASSAMESE']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['BENGALI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['GUJARATI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['HINDI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['KANNADA']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['KERALA']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['MARATHI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['MARWADI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['ORIYA']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['PARSI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['PUNJABI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['SINDHI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['TAMIL']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['TELUGU']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['URDU']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['KASHMIRI']['HORODISTRICT'] = 'horodistrict';
$DOMAINTABLE['RAJASTANI']['HORODISTRICT'] = 'horodistrict';


$DOMAINTABLE['ASSAMESE']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['BENGALI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['GUJARATI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['HINDI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['KANNADA']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['KERALA']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['MARATHI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['MARWADI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['ORIYA']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['PARSI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['PUNJABI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['SINDHI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['TAMIL']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['TELUGU']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['URDU']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['KASHMIRI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';
$DOMAINTABLE['RAJASTANI']['HOROALLCOUNTRIESCITIES'] = 'horoallcountriescities';


$DOMAINTABLE['ASSAMESE']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['BENGALI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['GUJARATI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['HINDI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['KANNADA']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['KERALA']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['MARATHI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['MARWADI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['ORIYA']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['PARSI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['PUNJABI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['SINDHI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['TAMIL']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['TELUGU']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['URDU']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['KASHMIRI']['CONTACTHISTORY'] = 'contacthistory';
$DOMAINTABLE['RAJASTANI']['CONTACTHISTORY'] = 'contacthistory';


$DOMAINTABLE['ASSAMESE']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['BENGALI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['GUJARATI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['HINDI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['KANNADA']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['KERALA']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['MARATHI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['MARWADI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['ORIYA']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['PARSI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['PUNJABI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['SINDHI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['TAMIL']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['TELUGU']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['URDU']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['KASHMIRI']['DRAFTSINFO'] = 'draftsinfo';
$DOMAINTABLE['RAJASTANI']['DRAFTSINFO'] = 'draftsinfo';


$DOMAINTABLE['ASSAMESE']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['BENGALI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['GUJARATI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['HINDI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['KANNADA']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['KERALA']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['MARATHI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['MARWADI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['ORIYA']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['PARSI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['PUNJABI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['SINDHI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['TAMIL']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['TELUGU']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['URDU']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['KASHMIRI']['EXPINTUSERTRACK'] = 'expintusertrack';
$DOMAINTABLE['RAJASTANI']['EXPINTUSERTRACK'] = 'expintusertrack';


$DOMAINTABLE['ASSAMESE']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['BENGALI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['GUJARATI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['HINDI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['KANNADA']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['KERALA']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['MARATHI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['MARWADI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['ORIYA']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['PARSI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['PUNJABI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['SINDHI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['TAMIL']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['TELUGU']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['URDU']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['KASHMIRI']['FOLDERINFO'] = 'folderinfo';
$DOMAINTABLE['RAJASTANI']['FOLDERINFO'] = 'folderinfo';


$DOMAINTABLE['ASSAMESE']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['BENGALI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['GUJARATI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['HINDI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['KANNADA']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['KERALA']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['MARATHI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['MARWADI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['ORIYA']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['PARSI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['PUNJABI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['SINDHI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['TAMIL']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['TELUGU']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['URDU']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['KASHMIRI']['INTERESTPENDING'] = 'interestpending';
$DOMAINTABLE['RAJASTANI']['INTERESTPENDING'] = 'interestpending';


$DOMAINTABLE['ASSAMESE']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['BENGALI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['GUJARATI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['HINDI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['KANNADA']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['KERALA']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['MARATHI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['MARWADI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['ORIYA']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['PARSI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['PUNJABI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['SINDHI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['TAMIL']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['TELUGU']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['URDU']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['KASHMIRI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';
$DOMAINTABLE['RAJASTANI']['INTERESTPENDINGUNVALIDATED'] = 'interestpendingunvalidated';


$DOMAINTABLE['ASSAMESE']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['BENGALI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['GUJARATI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['HINDI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['KANNADA']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['KERALA']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['MARATHI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['MARWADI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['ORIYA']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['PARSI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['PUNJABI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['SINDHI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['TAMIL']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['TELUGU']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['URDU']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['KASHMIRI']['MESSAGEPENDING'] = 'messagepending';
$DOMAINTABLE['RAJASTANI']['MESSAGEPENDING'] = 'messagepending';


$DOMAINTABLE['ASSAMESE']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['BENGALI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['GUJARATI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['HINDI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['KANNADA']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['KERALA']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['MARATHI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['MARWADI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['ORIYA']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['PARSI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['PUNJABI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['SINDHI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['TAMIL']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['TELUGU']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['URDU']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['KASHMIRI']['SPECIALALERT'] = 'specialalert';
$DOMAINTABLE['RAJASTANI']['SPECIALALERT'] = 'specialalert';


$DOMAINTABLE['ASSAMESE']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['BENGALI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['GUJARATI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['HINDI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['KANNADA']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['KERALA']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['MARATHI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['MARWADI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['ORIYA']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['PARSI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['PUNJABI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['SINDHI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['TAMIL']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['TELUGU']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['URDU']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['KASHMIRI']['USERTRACK'] = 'usertrack';
$DOMAINTABLE['RAJASTANI']['USERTRACK'] = 'usertrack';


$DOMAINTABLE['ASSAMESE']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['BENGALI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['GUJARATI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['HINDI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['KANNADA']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['KERALA']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['MARATHI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['MARWADI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['ORIYA']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['PARSI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['PUNJABI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['SINDHI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['TAMIL']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['TELUGU']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['URDU']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['KASHMIRI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';
$DOMAINTABLE['RAJASTANI']['USPAIDMSGPENDING'] = 'uspaidmsgpending';


$DOMAINTABLE['ASSAMESE']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['BENGALI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['GUJARATI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['HINDI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['KANNADA']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['KERALA']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['MARATHI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['MARWADI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['ORIYA']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['PARSI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['PUNJABI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['SINDHI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['TAMIL']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['TELUGU']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['URDU']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['KASHMIRI']['ADDREFERENCE'] = 'addreference';
$DOMAINTABLE['RAJASTANI']['ADDREFERENCE'] = 'addreference';


$DOMAINTABLE['ASSAMESE']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['BENGALI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['GUJARATI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['HINDI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['KANNADA']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['KERALA']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['MARATHI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['MARWADI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['ORIYA']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['PARSI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['PUNJABI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['SINDHI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['TAMIL']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['TELUGU']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['URDU']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['KASHMIRI']['ASTROMATCH'] = 'astromatch';
$DOMAINTABLE['RAJASTANI']['ASTROMATCH'] = 'astromatch';


$DOMAINTABLE['ASSAMESE']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['BENGALI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['GUJARATI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['HINDI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['KANNADA']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['KERALA']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['MARATHI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['MARWADI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['ORIYA']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['PARSI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['PUNJABI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['SINDHI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['TAMIL']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['TELUGU']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['URDU']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['KASHMIRI']['ASTROMATCHPARTNER'] = 'astromatchpartner';
$DOMAINTABLE['RAJASTANI']['ASTROMATCHPARTNER'] = 'astromatchpartner';


$DOMAINTABLE['ASSAMESE']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['BENGALI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['GUJARATI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['HINDI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['KANNADA']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['KERALA']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['MARATHI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['MARWADI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['ORIYA']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['PARSI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['PUNJABI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['SINDHI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['TAMIL']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['TELUGU']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['URDU']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['KASHMIRI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';
$DOMAINTABLE['RAJASTANI']['ASTROMATCHPACKAGEDET'] = 'astromatchpackagedet';


$DOMAINTABLE['ASSAMESE']['IGNORED'] = 'ignored';
$DOMAINTABLE['BENGALI']['IGNORED'] = 'ignored';
$DOMAINTABLE['GUJARATI']['IGNORED'] = 'ignored';
$DOMAINTABLE['HINDI']['IGNORED'] = 'ignored';
$DOMAINTABLE['KANNADA']['IGNORED'] = 'ignored';
$DOMAINTABLE['KERALA']['IGNORED'] = 'ignored';
$DOMAINTABLE['MARATHI']['IGNORED'] = 'ignored';
$DOMAINTABLE['MARWADI']['IGNORED'] = 'ignored';
$DOMAINTABLE['ORIYA']['IGNORED'] = 'ignored';
$DOMAINTABLE['PARSI']['IGNORED'] = 'ignored';
$DOMAINTABLE['PUNJABI']['IGNORED'] = 'ignored';
$DOMAINTABLE['SINDHI']['IGNORED'] = 'ignored';
$DOMAINTABLE['TAMIL']['IGNORED'] = 'ignored';
$DOMAINTABLE['TELUGU']['IGNORED'] = 'ignored';
$DOMAINTABLE['URDU']['IGNORED'] = 'ignored';
$DOMAINTABLE['KASHMIRI']['IGNORED'] = 'ignored';
$DOMAINTABLE['RAJASTANI']['IGNORED'] = 'ignored';


$DOMAINTABLE['ASSAMESE']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['BENGALI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['GUJARATI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['HINDI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['KANNADA']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['KERALA']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['MARATHI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['MARWADI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['ORIYA']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['PARSI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['PUNJABI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['SINDHI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['TAMIL']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['TELUGU']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['URDU']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['KASHMIRI']['BOOKMARKED'] = 'bookmarked';
$DOMAINTABLE['RAJASTANI']['BOOKMARKED'] = 'bookmarked';


$DOMAINTABLE['ASSAMESE']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['BENGALI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['GUJARATI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['HINDI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['KANNADA']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['KERALA']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['MARATHI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['MARWADI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['ORIYA']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['PARSI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['PUNJABI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['SINDHI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['TAMIL']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['TELUGU']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['URDU']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['KASHMIRI']['CONTACTINFO'] = 'contactinfo';
$DOMAINTABLE['RAJASTANI']['CONTACTINFO'] = 'contactinfo';


$DOMAINTABLE['ASSAMESE']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['BENGALI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['GUJARATI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['HINDI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['KANNADA']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['KERALA']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['MARATHI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['MARWADI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['ORIYA']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['PARSI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['PUNJABI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['SINDHI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['TAMIL']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['TELUGU']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['URDU']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['KASHMIRI']['HOROCITIES'] = 'horocities';
$DOMAINTABLE['RAJASTANI']['HOROCITIES'] = 'horocities';


$DOMAINTABLE['ASSAMESE']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['BENGALI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['GUJARATI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['HINDI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['KANNADA']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['KERALA']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['MARATHI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['MARWADI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['ORIYA']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['PARSI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['PUNJABI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['SINDHI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['TAMIL']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['TELUGU']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['URDU']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['KASHMIRI']['HOROCOUNTRIES'] = 'horocountries';
$DOMAINTABLE['RAJASTANI']['HOROCOUNTRIES'] = 'horocountries';


$DOMAINTABLE['ASSAMESE']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['BENGALI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['GUJARATI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['HINDI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['KANNADA']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['KERALA']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['MARATHI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['MARWADI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['ORIYA']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['PARSI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['PUNJABI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['SINDHI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['TAMIL']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['TELUGU']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['URDU']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['KASHMIRI']['HORODETAILS'] = 'horodetails';
$DOMAINTABLE['RAJASTANI']['HORODETAILS'] = 'horodetails';


$DOMAINTABLE['ASSAMESE']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['BENGALI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['GUJARATI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['HINDI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['KANNADA']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['KERALA']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['MARATHI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['MARWADI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['ORIYA']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['PARSI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['PUNJABI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['SINDHI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['TAMIL']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['TELUGU']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['URDU']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['KASHMIRI']['HOROINDIANSTATES'] = 'horoindianstates';
$DOMAINTABLE['RAJASTANI']['HOROINDIANSTATES'] = 'horoindianstates';


$DOMAINTABLE['ASSAMESE']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['BENGALI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['GUJARATI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['HINDI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['KANNADA']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['KERALA']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['MARATHI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['MARWADI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['ORIYA']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['PARSI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['PUNJABI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['SINDHI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['TAMIL']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['TELUGU']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['URDU']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['KASHMIRI']['HORONRISTATES'] = 'horonristates';
$DOMAINTABLE['RAJASTANI']['HORONRISTATES'] = 'horonristates';


$DOMAINTABLE['ASSAMESE']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['BENGALI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['GUJARATI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['HINDI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['KANNADA']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['KERALA']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['MARATHI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['MARWADI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['ORIYA']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['PARSI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['PUNJABI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['SINDHI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['TAMIL']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['TELUGU']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['URDU']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['KASHMIRI']['MATRIMONYID'] = 'matrimonyid';
$DOMAINTABLE['RAJASTANI']['MATRIMONYID'] = 'matrimonyid';


$DOMAINTABLE['ASSAMESE']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['BENGALI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['GUJARATI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['HINDI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['KANNADA']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['KERALA']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['MARATHI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['MARWADI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['ORIYA']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['PARSI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['PUNJABI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['SINDHI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['TAMIL']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['TELUGU']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['URDU']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['KASHMIRI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';
$DOMAINTABLE['RAJASTANI']['MATRIMONYPROFILEPARTLYREG'] = 'matrimonyprofilepartlyreg';

$DOMAINTABLE['ASSAMESE']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['BENGALI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['GUJARATI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['HINDI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['KANNADA']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['KERALA']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['MARATHI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['MARWADI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['ORIYA']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['PARSI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['PUNJABI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['SINDHI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['TAMIL']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['TELUGU']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['URDU']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['KASHMIRI']['REFEREEDETAILS'] = 'refereedetails';
$DOMAINTABLE['RAJASTANI']['REFEREEDETAILS'] = 'refereedetails';


$DOMAINTABLE['ASSAMESE']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['BENGALI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['GUJARATI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['HINDI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['KANNADA']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['KERALA']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['MARATHI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['MARWADI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['ORIYA']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['PARSI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['PUNJABI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['SINDHI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['TAMIL']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['TELUGU']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['URDU']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['KASHMIRI']['REFERENCESETTING'] = 'referencesetting';
$DOMAINTABLE['RAJASTANI']['REFERENCESETTING'] = 'referencesetting';


$DOMAINTABLE['ASSAMESE']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['BENGALI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['GUJARATI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['HINDI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['KANNADA']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['KERALA']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['MARATHI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['MARWADI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['ORIYA']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['PARSI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['PUNJABI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['SINDHI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['TAMIL']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['TELUGU']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['URDU']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['KASHMIRI']['SAVESEARCH'] = 'savesearch';
$DOMAINTABLE['RAJASTANI']['SAVESEARCH'] = 'savesearch';


$DOMAINTABLE['ASSAMESE']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['BENGALI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['GUJARATI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['HINDI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['KANNADA']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['KERALA']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['MARATHI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['MARWADI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['ORIYA']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['PARSI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['PUNJABI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['SINDHI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['TAMIL']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['TELUGU']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['URDU']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['KASHMIRI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';
$DOMAINTABLE['RAJASTANI']['VIEWHISTORYARCHIVE'] = 'viewhistoryarchive';


$DOMAINTABLE['ASSAMESE']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['BENGALI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['GUJARATI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['HINDI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['KANNADA']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['KERALA']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['MARATHI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['MARWADI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['ORIYA']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['PARSI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['PUNJABI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['SINDHI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['TAMIL']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['TELUGU']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['URDU']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['KASHMIRI']['VIEWHISTORY'] = 'viewhistory';
$DOMAINTABLE['RAJASTANI']['VIEWHISTORY'] = 'viewhistory';

$DOMAINTABLE['ASSAMESE']['MATCHWATCHARCHIVE'] = 'assamesematchwatcharchive';
$DOMAINTABLE['BENGALI']['MATCHWATCHARCHIVE'] = 'bengalimatchwatcharchive';
$DOMAINTABLE['GUJARATI']['MATCHWATCHARCHIVE'] = 'gujaratimatchwatcharchive';
$DOMAINTABLE['HINDI']['MATCHWATCHARCHIVE'] = 'hindimatchwatcharchive';
$DOMAINTABLE['KANNADA']['MATCHWATCHARCHIVE'] = 'kannadamatchwatcharchive';
$DOMAINTABLE['KERALA']['MATCHWATCHARCHIVE'] = 'keralamatchwatcharchive';
$DOMAINTABLE['MARATHI']['MATCHWATCHARCHIVE'] = 'marathimatchwatcharchive';
$DOMAINTABLE['MARWADI']['MATCHWATCHARCHIVE'] = 'marwadimatchwatcharchive';
$DOMAINTABLE['ORIYA']['MATCHWATCHARCHIVE'] = 'oriyamatchwatcharchive';
$DOMAINTABLE['PARSI']['MATCHWATCHARCHIVE'] = 'parsimatchwatcharchive';
$DOMAINTABLE['PUNJABI']['MATCHWATCHARCHIVE'] = 'punjabimatchwatcharchive';
$DOMAINTABLE['SINDHI']['MATCHWATCHARCHIVE'] = 'sindhimatchwatcharchive';
$DOMAINTABLE['TAMIL']['MATCHWATCHARCHIVE'] = 'tamilmatchwatcharchive';
$DOMAINTABLE['TELUGU']['MATCHWATCHARCHIVE'] = 'telugumatchwatcharchive';
$DOMAINTABLE['URDU']['MATCHWATCHARCHIVE'] = 'urdumatchwatcharchive';


// Single Table //
$TABLE['PHONEPACKAGEDET'] = 'phonepackagedet';
$TABLE['PHONEREQUESTLIST'] = 'phonerequestlist';
$TABLE['ASSUREDCONTACT'] = 'assuredcontact';
$TABLE['ASSUREDCONTACTBEFOREVALIDATION'] = 'assuredcontactbeforevalidation';
$TABLE['IVRFAILURES'] = 'ivrfailures';
$TABLE['LOGININFODATE'] = 'logininfodate';
$TABLE['MATRIMONYPROFILEDATE'] = 'matrimonyprofiledate';
$TABLE['MATRIMONYPROFILEDEL'] = 'matrimonyprofiledel';
$TABLE['MATRIMONYPROFILEMOD'] = 'matrimonyprofilemod';
$TABLE['PHOTOINFOLOG'] = 'photoinfolog';
$TABLE['MEMBERLOGINLOG'] = 'memberloginlog';
$TABLE['MEMBERLOGINLOGARCHIVE'] = 'memberloginlogarchive';
$TABLE['STAMP'] = 'stamp';
$TABLE['STAMPBEFOREVALIDATION'] = 'stampbeforevalidation';
$TABLE['VERIFYDET'] = 'verifydet';
$TABLE['ASTROPRODUCTS'] = 'astroproducts';
$TABLE['ASTROPRODUCTSCITIES'] = 'astroproductscities';
$TABLE['ASTROPRODUCTSCOUNTRIES'] = 'astroproductscountries';
$TABLE['ASTROPRODUCTSDISTRICT'] = 'astroproductsdistrict';
$TABLE['ASTROPRODUCTSDISTRICTOTHERS'] = 'astroproductsdistrictothers';
$TABLE['ASTROPRODUCTSINDIANSTATES'] = 'astroproductsindianstates';
$TABLE['ASTROPRODUCTSNRISTATES'] = 'astroproductsnristates';
$TABLE['CLASSIFIEDADVTS'] = 'classifiedadvts';
$TABLE['CLASSIFIEDORDERSDET'] = 'classifiedordersdet';
$TABLE['SMARTPACKDET'] = 'smartpackdet';
$TABLE['EVENTCONFIG'] = 'eventconfig';
$TABLE['GUJARATINRIMEET'] = 'gujaratinrimeet';
$TABLE['NYSINGLESMEET'] = 'nysinglesmeet';
$TABLE['NJSINGLESMEET'] = 'njsinglesmeet';
$TABLE['AUSSINGLESMEET'] = 'aussinglesmeet';
$TABLE['BMMATRIMONYMEET'] = 'bmmatrimonymeet';
$TABLE['USSINGLESMEET'] = 'ussinglesmeet';
$TABLE['FRANCHISEE'] = 'franchisee';
$TABLE['FRANCHISEPAYMENTS'] = 'franchisepayments';
$TABLE['FRUPGRADES'] = 'frupgrades';
$TABLE['INDIATODAYADS'] = 'indiatodayads';
$TABLE['INDIATODAYADCOUNTER'] = 'indiatodayadcounter';
$TABLE['DINAKARANADS'] = 'dinakaranads';
$TABLE['GULFNEWSADS'] = 'gulfnewsads';
$TABLE['ONLINESWAYAMVARAMCHATCONFIGURATIONS'] = 'onlineswayamvaramchatconfigurations';
$TABLE['ONLINESWAYAMVARAM'] = 'onlineswayamvaram';
$TABLE['OMMSURVEY'] = 'ommsurvey';
$TABLE['ONLINESWAYAMVARAMCHATLOG'] = 'onlineswayamvaramchatlog';
$TABLE['ONLINESWAYAMVARAMARCHIVELOG'] = 'onlineswayamvaramarchivelog';
$TABLE['ONLINESWAYAMVARAMCHATSTATUS'] = 'onlineswayamvaramchatstatus';
$TABLE['SMSBIRTHDAYWISH'] = 'smsbirthdaywish';
$TABLE['SMSDIWALIOFFER'] = 'smsdiwalioffer';
$TABLE['SMSPAIDMEMBER'] = 'smspaidmember';
$TABLE['SMSPAYMENTREMINDER'] = 'smspaymentreminder';
$TABLE['SMSWELCOMEMESSAGE'] = 'smswelcomemessage';
$TABLE['WDPAYMENTDETAILS'] = 'wdpaymentdetails';
$TABLE['WEDDINGDIRECTORY'] = 'weddingdirectory';
$TABLE['WDRESELLERDET'] = 'wdresellerdet';
$TABLE['WDREPORTAD'] = 'wdreportad';
$TABLE['ADVREVIEW'] = 'advreview';
$TABLE['ADVSMS'] = 'advsms';
$TABLE['IMGPURGEQUEUE'] = 'imgpurgequeue';
$TABLE['ADMININFO'] = 'admininfo';
$TABLE['BOUNCEEMAIL'] = 'bounceemail';
$TABLE['EMAILTEMPLATE'] = 'emailtemplate';
$TABLE['LANGPROFILESTATS'] = 'langprofilestats';
$TABLE['LOGININFO'] = 'logininfo';
$TABLE['MAILERPROFILE'] = 'mailerprofile';
$TABLE['MAILSUBSCRIBE'] = 'mailsubscribe';
$TABLE['MATRIMONYPROFILE'] = 'matrimonyprofile';
$TABLE['PARTLYREGCASE1'] = 'partlyregcase1';
$TABLE['MOBILEALERTMSG'] = 'mobilealertmsg';
$TABLE['MOBILEALERTS'] = 'mobilealerts';
$TABLE['MOBILEOPR'] = 'mobileopr';
$TABLE['SENDALERTS'] = 'sendalerts';
$TABLE['ASSUREDCONTACTPINNOSERIES'] = 'assuredcontactpinnoseries';
$TABLE['VOICEMATRIMONYPINNOSERIES'] = 'voicematrimonypinnoseries';
$TABLE['FAMILYINFO'] = 'familyinfo';
$TABLE['FILTERINFO'] = 'filterinfo';
$TABLE['HOBBIESINFO'] = 'hobbiesinfo';
$TABLE['LOGININFO'] = 'logininfo';
$TABLE['MATCHWATCH'] = 'matchwatch';
$TABLE['PHOTOINFO'] = 'photoinfo';
$TABLE['MATRIMONYPROFILE'] = 'matrimonyprofile';
$TABLE['PROFILEMATCH'] = 'profilematch';
$TABLE['FAMILYINFO'] = 'familyinfo';
$TABLE['FILTERINFO'] = 'filterinfo';
$TABLE['HOBBIESINFO'] = 'hobbiesinfo';
$TABLE['LOGININFO'] = 'logininfo';
$TABLE['MATCHWATCH'] = 'matchwatch';
$TABLE['PHOTOINFO'] = 'photoinfo';
$TABLE['MATRIMONYPROFILE'] = 'matrimonyprofile';
$TABLE['ADMINASSUREDINTERFACEPROFILE'] = 'adminassuredinterfaceprofile';
$TABLE['ADMINASSUREDINTERFACEUSERCREATION'] = 'adminassuredinterfaceusercreation';
$TABLE['TELEMARKETINGFOLLOWUPDETAILS'] = 'telemarketingfollowupdetails';
$TABLE['TELEMARKETING'] = 'telemarketing';
$TABLE['TELEMARKUSERCREATION'] = 'telemarkusercreation';
$TABLE['REGISTEREDVIABMC'] = 'registeredviabmc';
$TABLE['PAYMENTDETAILS'] = 'paymentdetails';
$TABLE['TELEMARKPOPULATE'] = 'telemarkpopulate';
$TABLE['MATRIMONYPROFILE'] = 'matrimonyprofile';
$TABLE['FOBRANCHDETAILS'] = 'fobranchdetails';
$TABLE['FOCUSTOMERDETAILS'] = 'focustomerdetails';
$TABLE['FOFOLLOWUPLOG'] = 'fofollowuplog';
$TABLE['FOLOGINDETAILS'] = 'fologindetails';
$TABLE['FOPAYMENTMADEDETAILS'] = 'fopaymentmadedetails';
$TABLE['FRONTOFFICELOGININFO'] = 'frontofficelogininfo';
$TABLE['FRONTOFFICESUPPORT'] = 'frontofficesupport';
$TABLE['EASYPAYBRANCHDETAILS'] = 'easypaybranchdetails';
$TABLE['EASYPAYHISTORYLOG'] = 'easypayhistorylog';
$TABLE['EASYPAYINFO'] = 'easypayinfo';
$TABLE['EASYPAYLOGINDETAILS'] = 'easypaylogindetails';
$TABLE['MATRIMONYPROFILE'] = 'matrimonyprofile';
$TABLE['PAYMENTDETAILS'] = 'paymentdetails';
$TABLE['ONLINESUPPORT'] = 'onlinesupport';
$TABLE['ASTROMATCHPAYMENTDETAILS'] = 'astromatchpaymentdetails';
$TABLE['AUTORENEWCHARGE'] = 'autorenewcharge';
$TABLE['AUTORENEWREFUND'] = 'autorenewrefund';
$TABLE['BIRTHDAYOFFER'] = 'birthdayoffer';
$TABLE['BMGIFTCOUPON'] = 'bmgiftcoupon';
$TABLE['BMGIFTSUBSCRIBE'] = 'bmgiftsubscribe';
$TABLE['CITIAUTH'] = 'citiauth';
$TABLE['CITITRACE'] = 'cititrace';
$TABLE['CITISER'] = 'citiser';
$TABLE['DUBAISCRATCHCARD'] = 'dubaiscratchcard';
$TABLE['EXPRESSINTERESTONEMONTHOFFER'] = 'expressinterestonemonthoffer';
$TABLE['MAXMINDUSPAYTRACK'] = 'maxminduspaytrack';
$TABLE['ONLINEPAYMENTFAILURES'] = 'onlinepaymentfailures';
$TABLE['PAYMENTDETAILS'] = 'paymentdetails';
$TABLE['PHONEPAYMENTDET'] = 'phonepaymentdet';
$TABLE['POSTOFFICECOUPON'] = 'postofficecoupon';
$TABLE['POWERPACKPAYMENTDET'] = 'powerpackpaymentdet';
$TABLE['SIFYCOUPON'] = 'sifycoupon';
$TABLE['USDECLINECOUNT'] = 'usdeclinecount';
$TABLE['ONLINEPAYMENTDETAILS'] = 'onlinepaymentdetails';
$TABLE['ONLINEPAYMENTQUEUE'] = 'onlinepaymentqueue';
$TABLE['CJCITIAUTH'] = 'cjcitiauth';
$TABLE['CJCITITRACE'] = 'cjcititrace';
$TABLE['CJONLINEPAYMENTDETAILS'] = 'cjonlinepaymentdetails';
$TABLE['INDEXQ'] = 'indexq';
$TABLE['MATRIOTHER'] = 'matriother';
$TABLE['ICSTATUS'] = 'icstatus';
$TABLE['CJBMMEMBERS'] = 'cjbmmembers';
$TABLE['RURALESEVAPROFILE'] = 'ruralesevaprofile';
$TABLE['EXPINTERESTONEMONTHOFFER'] = 'expinterestonemonthoffer';
$TABLE['MATCHWATCHMAIL'] = 'matchwatchmail';
?>