<?php
/* ************************************************************************************************** */
/* File		: bmip.inc
/* Author	: Ashokkumar, Mano, Kumaran, Saravanan
/* Date		: 10-Dec-2007
/* ************************************************************************************************** */
/* Description	:
/*     This inc file have DB and Application server IP's list as array's
/* ************************************************************************************************** */


$DBCONIP['DB15'] = '172.29.22.100'; //  For CBS Datasource

$GLOBALS['DBCONIP'] = $DBCONIP;

?>
